# Generated by Django 4.0.4 on 2022-04-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_date', models.DateField()),
                ('exit_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_code', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=2)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HKUMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hku_id', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('visited', models.ManyToManyField(through='core.EntryExit', to='core.venues')),
            ],
        ),
        migrations.AddField(
            model_name='entryexit',
            name='hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hkumembers'),
        ),
        migrations.AddField(
            model_name='entryexit',
            name='venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venues'),
        ),
    ]
