# Generated by Django 4.0.4 on 2022-04-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_code', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=2)),
                ('capacity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HKUMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hku_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('visited', models.ManyToManyField(through='core.EntryExit', to='core.venue')),
            ],
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hkumember'),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
        migrations.DeleteModel(
            name='HKUMembers',
        ),
        migrations.DeleteModel(
            name='Venues',
        ),
    ]
