# Generated by Django 4.0.4 on 2022-04-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venue_hkumember_alter_entryexit_hku_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('exit_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hkumember',
            name='visited',
        ),
        migrations.AddField(
            model_name='hkumember',
            name='entered_venue',
            field=models.ManyToManyField(related_name='entered_venue', through='core.Entry', to='core.venue'),
        ),
        migrations.AddField(
            model_name='hkumember',
            name='exited_venue',
            field=models.ManyToManyField(related_name='exited_venue', through='core.Exit', to='core.venue'),
        ),
        migrations.DeleteModel(
            name='EntryExit',
        ),
        migrations.AddField(
            model_name='exit',
            name='exit_hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_hku_id', to='core.hkumember'),
        ),
        migrations.AddField(
            model_name='exit',
            name='exit_venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_venue_code', to='core.venue'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_hku_id', to='core.hkumember'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_venue_code', to='core.venue'),
        ),
    ]
