# Generated by Django 4.0.4 on 2022-04-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_exit_remove_hkumember_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hkumember'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hkumember'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
    ]
