# Generated by Django 4.0.4 on 2022-04-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.hkumember', to_field='hku_id'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.venue', to_field='venue_code'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_hku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.hkumember', to_field='hku_id'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_venue_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.venue', to_field='venue_code'),
        ),
        migrations.AlterField(
            model_name='hkumember',
            name='hku_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
